# docker-compose.yml (A침adir servicio frontend)

services:
  # ... servicio mongo ...

  # ... servicio api ...

  # 游뚿 NUEVO SERVICIO: FRONTEND 游뚿
  frontend:
    build:
      context: . # Asume que el Dockerfile est치 en la ra칤z de tu proyecto
      dockerfile: Dockerfile.frontend # 游녣 Nombra el archivo Dockerfile para el frontend
    container_name: nextjs_frontend
    # En local, el frontend apunta a localhost:3000
    ports:
      - "3000:3000"
    # Aseg칰rate de que pueda hablar con la API (si est치 en el mismo archivo)
    environment:
      # URL de la API que consumir치 el frontend
      NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
    restart: always

volumes:
  mongo_data: